---

- name: Remove packages
  package: >
    name={{ item }}
    state=removed
  with_items: 
    - "{{os_security_packages_list}}"

- name: Install packages
  package: >
    name={{ item }}
    state=installed
  with_items: 
    - "{{packages}}"
...