---

- name: Template ssh banner
  template:
    src: templates/banner.j2
    dest: /etc/issue.net
    backup: no
    mode: 0644

- name: Template sshd config
  template: >
    src=templates/sshd.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    validate='/usr/sbin/sshd -t -f %s'
  notify: reload sshd
  
...